---
- name: Uninstall Docker and SFTPGo via SSM
  hosts: all
  become: yes
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "{{ ansible_aws_ssm_region }}"
    ansible_aws_ssm_bucket_name: "{{ ansible_aws_ssm_bucket_name }}"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Remove SFTPGo container
      docker_container:
        name: sftpgo
        state: absent
      ignore_errors: yes

    - name: Remove SFTPGo data directory
      file:
        path: /srv/sftpgo
        state: absent

    - name: Remove SFTPGo home directory
      file:
        path: /var/lib/sftpgo
        state: absent

    - name: Uninstall Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent

    - name: Remove Docker Compose
      file:
        path: /usr/local/bin/docker-compose
        state: absent
